services:
  postgres:
    image: postgres:17
    container_name: tp7-cineclub-postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5440:5432"
    volumes:
      - postgres_data_tp7:/var/lib/postgresql/data

volumes:
  postgres_data_tp7: